// importiamo le varie librerie e stili css
import TypeIt from "typeit";

import { createApp } from 'vue';
import './style.css';
import App from './App.vue';
import 'bootstrap/dist/css/bootstrap.css' ;
import  bootstrap from 'bootstrap/dist/js/bootstrap.bundle.js';
/* import the fontawesome core */
import { library } from '@fortawesome/fontawesome-svg-core';
/* import specific icons */

/* import font awesome icon component */
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

import axios from 'axios';



/* import specific icons */
import { faBars } from '@fortawesome/free-solid-svg-icons';

/* add icons to the library */
library.add(faBars)

import AOS from 'aos'
import 'aos/dist/aos.css'
AOS.init();

createApp(App).use(bootstrap).mount('#app')

new TypeIt("#element", { 
    lifeLike: false, 
    speed: 0 ,
	loop:true
})
	.delete(32, {instant: true})
	.type("S")
	.pause(138)
	.type("o")
	.pause(138)
	.type("n")
	.pause(490)
	.type("o")
	.pause(301)
	.type(" ")
	.pause(300)
	.type("u")
	.pause(104)
	.type("n")
	.pause(3602)
	.type(".")
	.pause(159)
	.type(".")
	.pause(142)
	.type(".")
	.pause(154)
	.type(".")
	.pause(157)
	.type(".")
	.pause(142)
	.type(".")
	.pause(729)
	.delete(1)
	.pause(512)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(35)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(29)
	.delete(1)
	.pause(36)
	.delete(1)
	.pause(30)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(2358)
	.type("s")
	.pause(199)
	.type("o")
	.pause(101)
	.type("n")
	.pause(153)
	.type("o")
	.pause(186)
	.type(" ")
	.pause(1034)
	.type("u")
	.pause(102)
	.type("n")
	.pause(607)
	.delete(1)
	.pause(509)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(1665)
	.type("w")
	.pause(102)
	.type("e")
	.pause(1102)
	.type("b")
	.pause(554)
	.type(" ")
	.pause(508)
	.type(" ")
	.pause(208)
	.type("d")
	.pause(735)
	.delete(1)
	.pause(510)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(35)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(2774)
	.type("U")
	.pause(426)
	.type("n")
	.pause(131)
	.type(" ")
	.pause(1372)
	.type("f")
	.pause(252)
	.type("r")
	.pause(131)
	.type("e")
	.pause(319)
	.type("o")
	.pause(152)
	.type("n")
	.pause(947)
	.delete(1)
	.pause(515)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(29)
	.delete(1)
	.pause(30)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(40)
	.delete(1)
	.pause(25)
	.delete(1)
	.pause(1162)
	.type("u")
	.pause(120)
	.type("n")
	.pause(236)
	.type(" ")
	.pause(1359)
	.type("b")
	.pause(178)
	.type("a")
	.pause(52)
	.type("s")
	.pause(163)
	.type("d")
	.pause(26)
	.type("k")
	.pause(228)
	.type("j")
	.pause(564)
	.delete(1)
	.pause(508)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(439)
	.type("a")
	.pause(510)
	.type("a")
	.pause(32)
	.type("a")
	.pause(33)
	.type("a")
	.pause(33)
	.type("a")
	.pause(33)
	.type("a")
	.pause(33)
	.type("a")
	.pause(34)
	.type("a")
	.pause(28)
	.type("a")
	.pause(33)
	.type("a")
	.pause(32)
	.type("a")
	.pause(32)
	.type("a")
	.pause(38)
	.type("a")
	.pause(30)
	.type("a")
	.pause(31)
	.type("a")
	.pause(33)
	.type("a")
	.pause(32)
	.type("a")
	.pause(644)
	.type("h")
	.pause(349)
	.delete(1)
	.pause(505)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(35)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(29)
	.delete(1)
	.pause(2757)
	.type("S")
	.pause(170)
	.type("O")
	.pause(115)
	.type("N")
	.pause(241)
	.type(" ")
	.pause(1061)
	.delete(1)
	.pause(510)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(626)
	.type("S")
	.pause(309)
	.type("O")
	.pause(106)
	.type("N")
	.pause(106)
	.type("O")
	.pause(238)
	.type(" ")
	.pause(413)
	.type("U")
	.pause(154)
	.type("N")
	.pause(194)
	.type(" ")
	.pause(565)
	.type("F")
	.pause(525)
	.type("U")
	.pause(409)
	.type("L")
	.pause(186)
	.type("L")
	.pause(885)
	.type("-")
	.pause(319)
	.type("S")
	.pause(383)
	.type("T")
	.pause(137)
	.type("A")
	.pause(660)
	.type("C")
	.pause(152)
	.type("K")
	.pause(476)
	.type(" ")
	.pause(1033)
	.type("W")
	.pause(124)
	.type("E")
	.pause(500)
	.type("B")
	.pause(193)
	.type(" ")
	.pause(333)
	.type("D")
	.pause(164)
	.type("E")
	.pause(373)
	.type("V")
	.pause(191)
	.type("E")
	.pause(293)
	.type("L")
	.pause(212)
	.type("O")
	.pause(173)
	.type("P")
	.pause(167)
	.type("E")
	.pause(113)
	.type("R")
	.pause(2253)
	.type("!")
	.pause(176)
	.type("!")
	.pause(164)
	.type("!")
	.pause(184)
	.type("!")
	.pause(151)
	.type("!")
	.pause(621)
	.delete(1)
	.pause(509)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(37)
	.delete(1)
	.pause(29)
	.delete(1)
	.pause(30)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(36)
	.delete(1)
	.pause(66)
	.delete(1)
	.pause(29)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(45)
	.delete(1)
	.pause(19)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(52)
	.delete(1)
	.pause(46)
	.delete(1)
	.pause(49)
	.delete(1)
	.pause(51)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(35)
	.delete(1)
	.pause(30)
	.delete(1)
	.pause(36)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(29)
	.delete(1)
	.pause(102)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(71)
	.delete(1)
	.pause(25)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(1507)
	.type("e")
	.pause(339)
	.type(" ")
	.pause(1340)
	.type("q")
	.pause(288)
	.type("u")
	.pause(219)
	.type("e")
	.pause(299)
	.type("s")
	.pause(252)
	.type("t")
	.pause(285)
	.type("o")
	.pause(185)
	.type(" ")
	.pause(1167)
	.type("è")
	.pause(1346)
	.delete(1)
	.pause(510)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(31)
	.delete(1)
	.pause(34)
	.delete(1)
	.pause(32)
	.delete(1)
	.pause(33)
	.delete(1)
	.pause(4933)
	.type("M")
	.pause(113)
	.type("Y")
	.pause(110)
	.type(" ")
	.pause(398)
	.type("P")
	.pause(106)
	.type("O")
	.pause(419)
	.type("R")
	.pause(123)
	.type("T")
	.pause(640)
	.type("F")
	.pause(160)
	.type("O")
	.pause(185)
	.type("L")
	.pause(270)
	.type("I")
	.pause(141)
	.type("O")
	.pause(141)
	
	.go();

	new TypeIt("#simpleUsage", {
		strings: "Sono Yari Narducci, un web developer appassionato di tecnologie e programmazione. Ho studiato presso il corso Boolean, dove ho acquisito una solida conoscenza delle principali tecnologie web, tra cui HTML, CSS, bootstrap,scss, JavaScript e Vue.js. Grazie a queste competenze, ho sviluppato siti web responsive e user-friendly, in grado di fornire un'esperienza di navigazione ottimale per gli utenti. Inoltre, ho approfondito la mia conoscenza del backend, studiando PHP, SQL e il framework Laravel. Queste competenze mi hanno permesso di creare siti web dinamici e complessi, in grado di gestire grandi quantità di dati e di fornire funzionalità avanzate agli utenti. Sono sempre alla ricerca di nuove sfide e di nuovi progetti su cui lavorare, con l'obiettivo di migliorare le mie competenze e offrire soluzioni innovative ai miei clienti. Sono convinto che la programmazione sia una disciplina in continua evoluzione, e sono pronto ad affrontare le sfide del futuro con entusiasmo e determinazione.",
		speed: 50,
		waitUntilVisible: true,
	  }).go();

	  function myMap() {
		var mapProp= {
		  center:new google.maps.LatLng(51.508742,-0.120850),
		  zoom:5,
		};
		var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
		}